Mvc_Program/checkboxmvc/checkboxmvc/Models/ErrorViewModel.cs
namespace checkboxmvc.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Mvc_Program/checkboxmvc/checkboxmvc/Models/Tea.cs
namespace checkboxmvc.Models
{
    public class Tea
    {
        public bool tea { get; set; }
        public bool Loundary { get; set; }
        public bool Breakfast { get; set; }
    }
}

Mvc_Program/checkboxmvc/checkboxmvc/Models/UserModel.cs
using Microsoft.AspNetCore.Components.Web;

namespace checkboxmvc.Models
{
    public class UserModel
    {
        public bool Tea { get; set; }
        public bool Loundary { get; set; }
        public bool Breakfast { get; set; }
    }
}

Mvc_Program/checkboxmvc/checkboxmvc/Controllers/HomeController.cs
using checkboxmvc.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace checkboxmvc.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }
       
        public IActionResult Index()
        {
           return View();
        }
        [HttpPost]
        public IActionResult Index(UserModel u)
        {
            ViewBag.tea = u.Tea;
            ViewBag.loundary = u.Loundary;
            ViewBag.breakfast = u.Breakfast;
            return View();
        }
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Mvc_Program/checkboxmvc/checkboxmvc/Controllers/TeaController.cs
using checkboxmvc.Models;
using Microsoft.AspNetCore.Mvc;

namespace checkboxmvc.Controllers
{
    public class TeaController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(Tea t)
        {
            if (t.tea == true)
            {
                ViewBag.tea = "You Selected Tea";
            }
            if (t.Loundary == true)
            {
                ViewBag.Loundary ="you selected loundary";
            }
            if(t.Breakfast == true)
            {
                ViewBag.Breakfast = "you selected breakfast";
            }
            return View();

        }
    }
}

Mvc_Program/checkboxmvc/checkboxmvc/Views/Tea/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model checkboxmvc.Models.Tea

@using (Html.BeginForm("Index", "Tea", FormMethod.Post))
{
    <b>Want Additional Benefit</b>
    <br />
    <span>Tea:</span>
    @Html.CheckBoxFor(m=>m.tea,true)
    <br />
    <span>Loundary:</span>
    @Html.CheckBoxFor(m=>m.Loundary,false)
    <br />
    <span>Breakfast:</span>
    @Html.CheckBoxFor(m=>m.Breakfast,false)
    <br />
    <input type="submit" value="Submit" />
}

<hr />
<h5>-----You Selected------</h5>
<br />
Tea:@ViewBag.tea
<br />
Loudary:@ViewBag.Loundary
<br />
Breakfast:@ViewBag.Breakfast